name: CI/CD Docker Workflow

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Rodar testes simples
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "âœ… Testes executados com sucesso!"

  build:
    name: Construir imagem Docker
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t lab-docker-ci:latest .

  publish:
    name: Publicar imagem no Docker Hub
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: |
          docker tag lab-docker-ci:latest ${{ secrets.DOCKERHUB_USERNAME }}/lab-docker-ci:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/lab-docker-ci:latest
