name: CI/CD Docker Workflow

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Rodar testes simples
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "âœ… Testes executados com sucesso!"

  build:
    name: Construir imagem Docker
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Verificar arquivos
        run: ls -la
      - name: Build da imagem Docker
        run: |
          echo "ðŸš§ Iniciando build..."
          docker build -t lukydark/lab-docker-ci:latest .
          echo "âœ… Build concluÃ­do!"
          docker images

  publish:
    name: Publicar imagem no Docker Hub
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Publicar imagem
        run: |
          echo "ðŸ“¤ Enviando imagem para o Docker Hub..."
          docker push lukydark/lab-docker-ci:latest
          echo "ðŸŽ‰ Imagem publicada com sucesso!"
